name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 新增依赖安装步骤
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libudev-dev  # 关键缺失依赖

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
